name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@2.0.0
    secrets: inherit
    with:
      provider: none
      enable_version_check: true
      working_directory: './examples/basic/'

 
  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@2.0.0
    secrets: inherit
    with:
      provider: none
      enable_version_check: true
      working_directory: './examples/complete/'

